---
- name: "Make agent Directory"
  ansible.builtin.file:
    path: "/etc/datasaker/{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  with_items:
    - "dsk-log-agent"

- name: "Create agent config"
  ansible.builtin.file:
    path: "{{ datasaker_host_path }}/dsk-log-agent/agent-config.yml"
    state: touch

- name: "Setting dsk-log-agent config"
  template:
    src: log-agent-config.yml.j2
    dest: "{{ datasaker_host_path }}/dsk-log-agent/agent-config.yml"