---
- name: Make Datasaker Host Agent Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  with_items:
    - "{{ datasaker_host_path }}"
  when:
  - ansible_facts.os_family in ["Debian", "RedHat"]
  - datasaker_agents

- name: "create Host Agent global-config"
  ansible.builtin.file:
    path: "{{ datasaker_host_path }}/global-config.yml"
    state: touch
  when:
  - ansible_facts.os_family in ["Debian", "RedHat"]
  - datasaker_agents    

- name: "Setting Host Agent global-config"
  template:
    src: global-config.yml.j2
    dest: "{{ datasaker_host_path }}/global-config.yml"
  when:
  - ansible_facts.os_family in ["Debian", "RedHat"]
  - datasaker_agents

- name: "Make Datasaker Docker Agent Directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ datasaker_docker_config_path }}"
  when:
  - datasaker_docker_agents

- name: "Create Docker Agent global-config"
  ansible.builtin.file:
    path: "{{ datasaker_docker_global_config }}"
    state: touch
  when:
  - datasaker_docker_agents

- name: "Setting Docker Agent global-config"
  template:
    src: global-config.yml.j2
    dest: "{{ datasaker_docker_global_config }}"
  when:
  - datasaker_docker_agents
