---
- name: Include Gather Ansible Facts task on Ansible >= 2.10
  include_tasks: gather-facts.yml
  when: ansible_version.major >= 2 and ansible_version.minor >= 10

- name: Include Datasaker Add Repository
  include_tasks: dsk-common.yml
  when: uninstall == False and ansible_facts.os_family == "Debian" or ansible_facts.os_family == "RedHat"

- name: Include Datasaker Debian Host Agent Install
  include_tasks: dsk-debian-pkg.yml
  when: uninstall == False and ansible_facts.os_family == "Debian"

- name: Include Datasaker RedHat Host Agent Install
  include_tasks: dsk-redhat-pkg.yml
  when: uninstall == False and ansible_facts.os_family == "RedHat"

- name: Uninstall Datasaker Agent
  include_tasks: remove-datasaker.yml
  when: uninstall == True
