---
- name: "Include Gather Ansible Facts task on Ansible >= 2.10"
  include_tasks: gather-facts.yml
  when: 
  - ansible_version.major >= 2
  - ansible_version.minor >= 10

- name: "Check Datasaker Agent List"
  set_fact:
    datasaker_agents: []
  when: datasaker_docker_agents | select('search', 'docker') | list | count > 0

- name: "Include Datasaker Add Directory Config"
  include_tasks: dsk-common.yml
  when: 
  - uninstall == False

- name: "Include Datasaker Debian Host Agent Install"
  include_tasks: dsk-debian-pkg.yml
  when: 
  - uninstall == False
  - ansible_facts.os_family == "Debian"
  - datasaker_agents

- name: "Include Datasaker RedHat Host Agent Install"
  include_tasks: dsk-redhat-pkg.yml
  when: 
  - uninstall == False
  - ansible_facts.os_family == "RedHat"
  - datasaker_agents

- name: "Include Datasaker Agent Install"
  include_tasks: check-agent.yml
  when: 
  - uninstall == False

- name: "Include Docker Agent Path Permissions Setting"
  include_tasks: permissions.yml
  when: 
  - uninstall == False
  - datasaker_docker_agents

- name: "Uninstall Datasaker Agent"
  include_tasks: remove-datasaker.yml
  when: 
  - uninstall == True
