- name: "Change owner and group of datasaker docker directory"
  ansible.builtin.file:
    path: /var/datasaker
    owner: "{{ datasaker_docker_user }}"
    group: "{{ datasaker_docker_group }}"
    recurse: yes
